#spring AI core
spring.ai.model.chat=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:1.5b
spring.ai.ollama.embedding.model=qwen3-embedding
# core
spring.application.name=Backend

# Database
spring.data.mongodb.url=${DATABASE}
spring.ai.vectorstore.mongodb.initialize-schema=false

#Spring security
spring.security.user.name=admin
spring.security.user.password=1111
server.port=8081
debug=false
