server.error.include-message=always
server.error.include-binding-errors=always
spring.application.name=Backend
spring.data.mongodb.url=mongodb://localhost:27017/
# Spring Security Default Credentials
spring.security.user.name=admin
spring.security.user.password=1111
server.port=8081
debug=false
